# Site settings
title: Mike Heijmans
email: parabuzzle@gmail.com
description: "Mike Heijmans has over 10 years of experience in the Tech and Finance industries. He is a Private Investor, Musician, Entertainer, Pilot, Tinkerer, and a total failure."
baseurl: ""
url: "http://www.mikeheijmans.com"
timezone: America/Los_Angeles
paginate: 5

author:
  name: Mike Heijmans
  email: parabuzzle@gmail.com
  uri: /about

twitter_username: parabuzzle
github_username:  parabuzzle
facebook_username: parabuzzle
linkedin_username: mheijmans
flickr_username: parabuzzle
instagram_username: parabuzzle
vimeo_username: parabuzzle

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
  auto_ids: true

# Build settings
markdown:    kramdown
permalink:   pretty
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

gist:
  noscript: false

gems:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-coffeescript
  - jemoji
  - jekyll-paginate