# Site settings
title: Mike Heijmans
email: parabuzzle@gmail.com
description: "Mike Heijmans has over 10 years of experience in the tech industry. He is a Builder, Rubyist, DevOps engineer, public speaker, and open source advocate."
baseurl: ""
url: "http://www.mikeheijmans.com"
timezone: America/Los_Angeles
paginate: 5

author:
  name: Mike Heijmans
  email: parabuzzle@gmail.com
  uri: /about

twitter_username: parabuzzle
github_username:  parabuzzle
facebook_username: parabuzzle
linkedin_username: mheijmans
flickr_username: parabuzzle
instagram_username: parabuzzle
vimeo_username: parabuzzle


# Build settings
markdown: redcarpet
permalink: pretty
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

gems:
  - jekyll-redirect-from
  - jemoji
  - jekyll-feed
